config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # you can delete this
  # devise_for :users
 
  resources :feats
  resources :features
  resources :spells
  resources :skills
  resources :weapons
  resources :armors do
    member do
      get 'edit' 
    end
  end
  resources :characters do
    resources :weapons
    resources :armors
    resources :feats
    resources :features
    resources :spells
    resources :skills

    member do
      post 'increase_level'
      post 'increase_health'
      post 'decrease_health' 
    end
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "characters#index"
end

app/models/weapon.rb
# == Schema Information
#
# Table name: weapons
#
#  id           :integer          not null, primary key
#  damage       :string
#  name         :string
#  weapon_type  :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  character_id :integer
#
class Weapon < ApplicationRecord
  validates(:character_id, presence: true)

  belongs_to(:characters, class_name: "Character", foreign_key: "character_id")
  
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :set_weapon, only: %i[ show edit update destroy ]
  before_action :set_character

  # GET /weapons or /weapons.json
  def index
    @weapons = @character.weapons
  end

  # GET /weapons/1 or /weapons/1.json
  def show
  end

  # GET /weapons/new
  def new
    @weapon = Weapon.new
  end

  # GET /weapons/1/edit
  def edit
  end

  # POST /weapons or /weapons.json
  def create
    @weapon = Weapon.new(weapon_params)

    respond_to do |format|
      if @weapon.save
        format.html { redirect_to weapon_url(@weapon), notice: "Weapon was successfully created." }
        format.json { render :show, status: :created, location: @weapon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weapons/1 or /weapons/1.json
  def update
    respond_to do |format|
      if @weapon.update(weapon_params)
        format.html { redirect_to (@character), notice: "Weapon was successfully updated." }
        format.json { render :show, status: :ok, location: character_weapon_url(@character, @weapon) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1 or /weapons/1.json
  def destroy
    @weapon.destroy

    respond_to do |format|
      format.html { redirect_to (@character), notice: 'Weapon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weapon
      @weapon = Weapon.find(params[:id])
    end

    def set_character
      @character =  Character.find(params[:character_id])
    end


    # Only allow a list of trusted parameters through.
    def weapon_params
      params.require(:weapon).permit(:damage, :weapon_type, :name, :character_id)
    end
end

app/views/weapons/_form.html.erb
<%= form_with(model: [@character, @weapon], local: true) do |form| %>
  <% if weapon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
        <% weapon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :damage, style: "display: block" %>
    <%= form.text_field :damage %>
  </div>

  <div>
    <%= form.label :weapon_type, style: "display: block" %>
    <%= form.text_field :weapon_type %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :character_id, style: "display: block" %>
    <%= form.hidden_field :character_id, value: @character.id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/weapons/_weapon.html.erb
<div id="<%= dom_id weapon %>">
  <div class="card"  style="width: 18rem;">
    <ul class="list-group list-group-flush" >
      <li class="list-group-item" id = "details">
        <p>
          <strong>Damage:</strong>
          <%= weapon.damage %>
        </p>

        <p>
          <strong>Weapon type:</strong>
          <%= weapon.weapon_type %>
        </p>

        <p>
          <strong>Name:</strong>
          <%= weapon.name %>
        </p>

        <%= link_to "Edit weapon", edit_character_weapon_path(@character, weapon) %>
        <%= button_to 'Delete armor', character_weapon_path(@character, weapon), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </li>
    </ul>
  </div>

</div>

app/views/weapons/edit.html.erb
<h1>Editing weapon</h1>

<%= render "form", weapon: @weapon %>

<br>

<div>
  <%= link_to "Back to character", (@character) %> 
</div>

app/views/weapons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Weapons</h1>

<div id="weapons">
  <% @weapons.each do |weapon| %>
    <%= render weapon %>
    <p>
      <%= link_to "Show this weapon", character_weapon_path(@character, weapon) %>
    </p>
  <% end %>
</div>

<%= link_to "New weapon", new_character_weapon_path(@character) %>

app/views/weapons/new.html.erb
<h1>New weapon</h1>

<%= render "form", weapon: @weapon %>

<br>

<div>
  <%= link_to "Back to weapons", weapons_path %>
</div>

app/views/weapons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @weapon %>

<div>
  <%= link_to "Edit this weapon", edit_weapon_path(@weapon) %> |
  <%= link_to "Back to weapons", weapons_path %>

  <%= button_to "Destroy this weapon", @weapon, method: :delete %>
</div>