config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # you can delete this
  # devise_for :users
 
  resources :feats
  resources :features
  resources :spells
  resources :skills
  resources :weapons
  resources :armors do
    member do
      get 'edit' 
    end
  end
  resources :characters do
    resources :weapons
    resources :armors
    resources :feats
    resources :features
    resources :spells
    resources :skills

    member do
      post 'increase_level'
      post 'increase_health'
      post 'decrease_health' 
    end
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "characters#index"
end

app/models/character.rb
# == Schema Information
#
# Table name: characters
#
#  id              :integer          not null, primary key
#  appearance      :string
#  armor_class     :integer
#  background      :string
#  character_class :string
#  charisma        :integer
#  constitution    :integer
#  current_health  :integer
#  dexterity       :integer
#  image           :string
#  intelligence    :integer
#  level           :integer
#  max_health      :integer
#  name            :string
#  proficiency     :string
#  race            :string
#  speed           :integer
#  strength        :integer
#  wisdom          :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#
class Character < ApplicationRecord
  has_many(:armors, class_name: "Armor", foreign_key: "character_id")
  has_many(:feats, class_name: "Feat", foreign_key: "character_id")
  has_many(:features, class_name: "Feature", foreign_key: "character_id")
  has_many(:skills, class_name: "Skill", foreign_key: "character_id")
  has_many(:spells, class_name: "Spell", foreign_key: "character_id")
  has_many(:weapons, class_name: "Weapon", foreign_key: "character_id")
  belongs_to(:user, class_name: "User", foreign_key: "user_id" )
  
  validates :name, presence: true
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]

  # GET /characters or /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1 or /characters/1.json
  def show
    authorize @character
    @character = Character.find(params[:id])
    @character_armors = @character.armors
    @armors = @character.armors.first

    @character = Character.find(params[:id])
    @character_weapons = @character.weapons
    @weapons = @character.weapons.first

    @character = Character.find(params[:id])
    @character_spells = @character.spells
    @spells = @character.spells.first

    @character = Character.find(params[:id])
    @character_feats = @character.feats
    @feats = @character.feats.first

    @character = Character.find(params[:id])
    @character_features = @character.features
    @features = @character.features.first

    @character = Character.find(params[:id])
    @character_skills = @character.skills
    @features = @character.features.first
  end

  # GET /characters/new
  def new
    @character = Character.new(user_id: current_user.id)
    
  end

  # GET /characters/1/edit
  def edit
  end


  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to character_url(@character), notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to character_url(@character), notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def increase_level
    @character = Character.find(params[:id])
    @character.increment!(:level)

    respond_to do |format|
      format.js
    end
  end

  def increase_health
    def increase_health
      @character = Character.find(params[:id])
      @character.increment!(:current_health)

      respond_to do |format|
        format.js
      end
    end
  end

  def decrease_health
    @character = Character.find(params[:id])
    @character.decrement!(:current_health)

    respond_to do |format|
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_character
    @character = Character.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def character_params
    params.require(:character).permit(:strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :level, :character_class, :appearance, :background, :user_id, :name, :armor_class, :max_health, :current_health, :race, :speed, :proficiency, :image)
  end
end

app/views/characters/_character.html.erb
<div id="<%= dom_id character %>">
  <div class="row">
    <div class="col-md-6">
      <p>
        <h1><%= character.name %></h1>
      </p>
      <p>
        <%= link_to(edit_character_path) do %>
<img src="<%= character.image %>" class="card-img-top" alt="<%= character.image.present? ? 'Log Image' : 'No Photo Uploaded' %>">
        <% end %>
      </p>

      <p>
        <div class="progress" style="height: 25px">
          <% current_health_percentage = (character.current_health.to_f / character.max_health) * 100 %>
          <div class="progress-bar bg-danger" role="progressbar" style="width: <%= current_health_percentage %>%" aria-valuenow=<%= character.current_health %> aria-valuemin="0" aria-valuemax=<%= character.max_health %>><span id="currentHealthBar"><%= character.current_health %></span></div>
        </div>
      </p>

      <p>
        <strong>Current Health:</strong>
        <span id="currentHealthDisplay"><%= character.current_health %></span>
        <%= link_to "<i class='fas fa-plus'></i>".html_safe, increase_health_character_path(character), method: :post, remote: true, class: "btn btn-success", id: "increaseHealthBtn" %>
        <%= link_to "<i class='fas fa-minus'></i>".html_safe, decrease_health_character_path(character), method: :post, remote: true, class: "btn btn-danger", id: "decreaseHealthBtn" %>
      </p>

      <p>
        <strong>Character class:</strong>
        <%= character.character_class %>
      </p>

      <p>
        <strong>Level:
          <%= character.level %> </strong>

        <%= link_to "<i id='levelUpIcon' class='fas fa-level-up-alt'></i>".html_safe, increase_level_character_path(character), method: :post, remote: true, class: "text-primary" %>

      </p>
    </div>

    <div class="col-md-6">
      <%= render partial: 'stat_card', locals: { character: character } %>

      <p>
        <strong>Appearance:</strong>
        <%= character.appearance %>
      </p>

      <p>
        <strong>Background:</strong>
        <%= character.background %>
      </p>

      <p>
        <strong>Armor class:</strong>
        <%= character.armor_class %>
      </p>

      <p>
        <strong>Race:</strong>
        <%= character.race %>
      </p>

      <p>
        <strong>Speed:</strong>
        <%= character.speed %>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= render "characters/partials/armor_modal" %>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#armorModal">Armors</button>
    </div>

    <div class="col-md-2">
      <%= render "characters/partials/weapon_modal" %>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#weaponModal">Weapons</button>
    </div>

    <div class="col-md-2">
      <%= render "characters/partials/spell_modal" %>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#spellModal">Spells</button>
    </div>

    <div class="col-md-2">
      <%= render "characters/partials/feat_modal" %>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#featModal">Feats</button>
    </div>

    <div class="col-md-2">
      <%= render "characters/partials/feature_modal" %>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#featureModal">Features</button>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%=render  "characters/stat_partials/strength" %>
      <%=render  "characters/stat_partials/dexterity" %>
      <%=render  "characters/stat_partials/intelligence" %>
      <%=render  "characters/stat_partials/constitution" %>
      <%=render  "characters/stat_partials/wisdom" %>
      <%=render  "characters/stat_partials/charisma" %>
    </div>
  </div>
</div>

app/views/characters/_character_card.html.erb
<% if current_user == character.user %>
  <div class = "card mb-4", style = "width: 18rem;">
    <div class = "card-body">
      <%= link_to character_path(character) do %>
<img src="<%= character.image %>" class="card-img-top" alt="<%= character.image.present? ? 'Log Image' : 'No Photo Uploaded' %>">
      <% end %>
<!--      -->
      <h5 class = "card-title"> <%=character.name%> </h5>
      <p class = "card-text">
        <strong>Class:</strong> <%= character.character_class%> 
      </p>
      <p class="card-text">
        <strong>Level:</strong> <%= character.level %>
      </p>
    </div>
  </div>
<%end%>

app/views/characters/_form.html.erb
<%= form_with(model: character) do |form| %>
  <% if character.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :strength, style: "display: block" %>
    <%= form.number_field :strength %>
  </div>

  <div>
    <%= form.label :dexterity, style: "display: block" %>
    <%= form.number_field :dexterity %>
  </div>

  <div>
    <%= form.label :constitution, style: "display: block" %>
    <%= form.number_field :constitution %>
  </div>

  <div>
    <%= form.label :intelligence, style: "display: block" %>
    <%= form.number_field :intelligence %>
  </div>

  <div>
    <%= form.label :wisdom, style: "display: block" %>
    <%= form.number_field :wisdom %>
  </div>

  <div>
    <%= form.label :charisma, style: "display: block" %>
    <%= form.number_field :charisma %>
  </div>

  <div>
    <%= form.label :level, style: "display: block" %>
    <%= form.number_field :level %>
  </div>

  <div>
    <%= form.label :character_class, style: "display: block" %>
    <%= form.text_field :character_class %>
  </div>

  <div>
    <%= form.label :appearance, style: "display: block" %>
    <%= form.text_field :appearance %>
  </div>

  <div>
    <%= form.label :background, style: "display: block" %>
    <%= form.text_field :background %>
  </div>

 <div>
    <%= form.label :user_id, style: "display: none" %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>


  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :armor_class, style: "display: block" %>
    <%= form.number_field :armor_class %>
  </div>

  <div>
    <%= form.label :max_health, style: "display: block" %>
    <%= form.number_field :max_health %>
  </div>

  <div>
    <%= form.label :current_health, style: "display: block" %>
    <%= form.number_field :current_health %>
  </div>

  <div>
    <%= form.label :race, style: "display: block" %>
    <%= form.text_field :race %>
  </div>

  <div>
    <%= form.label :speed, style: "display: block" %>
    <%= form.number_field :speed %>
  </div>

  <div>
    <%= form.label :proficiency, style: "display: block" %>
    <%= form.text_field :proficiency %>
  </div>

  <div>
    <%= form.label :image, style: "display: block", value:"https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/_landingpage.html.erb
<div id = land-body>
  This is an app to help Dungeons and Dragons players manage there characters. To start managing your characters, please sign up or sign in!
</div>

app/views/characters/_stat_card.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#strengthModal">
        Strength
      </button>

      <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#dexterityModal">
        Dexterity
      </button>

      <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#constitutionModal">
        Constitution
      </button>
    </div>
    <div class="col">

      <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#intelligenceModal">
        Intelligence
      </button>

      <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#wisdomModal">
        Wisdom
      </button>

      <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#charismaModal">
        Charisma
      </button>

    </div>
  </div>
</div>

app/views/characters/decrease_health.js.erb
var currentHealthDisplay = $("#currentHealthDisplay");
var newCurrentHealth = <%= @character.current_health %>;


currentHealthDisplay.text(newCurrentHealth);


var currentHealthPercentage = (newCurrentHealth / <%= @character.max_health.to_f %>) * 100;
$(".progress-bar").css("width", currentHealthPercentage + "%");

var currentHealthBar = $("#currentHealthBar");
var newCurrentHealthBar = <%= @character.current_health %>;


currentHealthBar.text(newCurrentHealthBar);

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render "form", character: @character %>

<br>

<div>
  <%= link_to "Show this character", @character %> |
  <%= link_to "Back to characters", characters_path %>
</div>

app/views/characters/increase_health.js.erb
var currentHealthDisplay = $("#currentHealthDisplay");
var newCurrentHealth = <%= @character.current_health %>;


currentHealthDisplay.text(newCurrentHealth);


var currentHealthPercentage = (newCurrentHealth / <%= @character.max_health.to_f %>) * 100;
$(".progress-bar").css("width", currentHealthPercentage + "%");

var currentHealthBar = $("#currentHealthBar");
var newCurrentHealthBar = <%= @character.current_health %>;


currentHealthBar.text(newCurrentHealthBar);

app/views/characters/increase_level.js.erb
var levelContainer = $("#<%= dom_id @character %> strong:contains('Level:')");

var newLevel = <%= @character.level %>;

levelContainer.html("Level: " + newLevel);

app/views/characters/index.html.erb
<%if  user_signed_in?%>
  <p style="color: green"><%= notice %></p>

  <div class="container mt-4">
    <p class="notice text-success"><%= notice %></p>

    <h1 class="text-center mb-4" id = "index-title">Characters</h1>

    <div class="row">
      <% @characters.each do |character| %>
        <div class= "col-md-3 mb-2">
          <%= render partial: 'character_card', locals: { character: character } %>
        </div>
      <% end %>
    </div>

    <%= link_to "New character", new_character_path, class: 'btn btn-success' %>
  </div>

<%else%>
  <%= render "landingpage"%>

<%end%>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render "form", character: @character %>

<br>

<div>
  <%= link_to "Back to characters", characters_path %>
</div>

app/views/characters/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @character %>

<div>
  <%= link_to "Edit this character", edit_character_path(@character) %> |
  <%= link_to "Back to characters", characters_path %>

  <%= button_to "Destroy this character", @character, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>