config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # you can delete this
  # devise_for :users
 
  resources :feats
  resources :features
  resources :spells
  resources :skills
  resources :weapons
  resources :armors do
    member do
      get 'edit' 
    end
  end
  resources :characters do
    resources :weapons
    resources :armors
    resources :feats
    resources :features
    resources :spells
    resources :skills

    member do
      post 'increase_level'
      post 'increase_health'
      post 'decrease_health' 
    end
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "characters#index"
end

app/models/spell.rb
# == Schema Information
#
# Table name: spells
#
#  id           :integer          not null, primary key
#  level        :integer
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  character_id :integer
#
class Spell < ApplicationRecord
  validates(:character_id, presence: true)

  belongs_to(:characters, class_name: "Character", foreign_key: "character_id")
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :set_spell, only: %i[ show edit update destroy ]
  before_action :set_character

  # GET /spells or /spells.json
  def index
    @spells = @character.spells
  end

  # GET /spells/1 or /spells/1.json
  def show
  end

  # GET /spells/new
  def new
    @spell = Spell.new
  end

  # GET /spells/1/edit
  def edit
  end

  # POST /spells or /spells.json
  def create
    @spell = Spell.new(spell_params)

    respond_to do |format|
      if @spell.save
        format.html { redirect_to spell_url(@spell), notice: "Spell was successfully created." }
        format.json { render :show, status: :created, location: @spell }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spells/1 or /spells/1.json
  def update
    respond_to do |format|
      if @spell.update(spell_params)
        format.html { redirect_to (@character), notice: "Spell was successfully updated." }
        format.json { render :show, status: :ok, location: character_spell_url(@character, @spell) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spells/1 or /spells/1.json
  def destroy
    @spell.destroy

    respond_to do |format|
      format.html { redirect_to (@character), notice: 'Spell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spell
      @spell = Spell.find(params[:id])
    end

    def set_character
      @character =  Character.find(params[:character_id])
    end

    # Only allow a list of trusted parameters through.
    def spell_params
      params.require(:spell).permit(:name, :level, :character_id)
    end
end

app/views/spells/_form.html.erb
<%= form_with(model: [@character, @spell], local: true) do |form| %>
  <% if spell.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spell.errors.count, "error") %> prohibited this spell from being saved:</h2>

      <ul>
        <% spell.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :level, style: "display: block" %>
    <%= form.number_field :level %>
  </div>

  <div>
    <%= form.label :character_id, style: "display: block" %>
    <%= form.hidden_field :character_id, value: @character.id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spells/_spell.html.erb
<div id="<%= dom_id spell %>">
  <div class="card"  style="width: 18rem;">
    <ul class="list-group list-group-flush" >
      <li class="list-group-item" id = "details">
        <p>
          <strong>Name:</strong>
          <%= spell.name %>
        </p>

        <p>
          <strong>Level:</strong>
          <%= spell.level %>
        </p>
        <%= link_to "Edit spell", edit_character_spell_path(@character, spell) %>
        <%= button_to 'Delete spell', character_spell_path(@character, spell), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </li>
    </ul>
  </div>

</div>

app/views/spells/edit.html.erb
<h1>Editing spell</h1>

<%= render "form", spell: @spell %>

<br>

<div>
  <%= link_to "Back to character", (@character) %> 
</div>

app/views/spells/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Spells</h1>

<div id="spells">
  <% @spells.each do |spell| %>
    <%= render spell %>
    <p>
      <%= link_to "Show this spell", character_spell_path(@character, spell) %>
    </p>
  <% end %>
</div>

<%= link_to "New spell", new_character_spell_path(@character) %>

app/views/spells/new.html.erb
<h1>New spell</h1>

<%= render "form", spell: @spell %>

<br>

<div>
  <%= link_to "Back to spells", spells_path %>
</div>

app/views/spells/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @spell %>

<div>
  <%= link_to "Edit this spell", edit_spell_path(@spell) %> |
  <%= link_to "Back to spells", spells_path %>

  <%= button_to "Destroy this spell", @spell, method: :delete %>
</div>