config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # you can delete this
  # devise_for :users
 
  resources :feats
  resources :features
  resources :spells
  resources :skills
  resources :weapons
  resources :armors do
    member do
      get 'edit' 
    end
  end
  resources :characters do
    resources :weapons
    resources :armors
    resources :feats
    resources :features
    resources :spells
    resources :skills

    member do
      post 'increase_level'
      post 'increase_health'
      post 'decrease_health' 
    end
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "characters#index"
end

app/models/armor.rb
# == Schema Information
#
# Table name: armors
#
#  id             :integer          not null, primary key
#  armor_category :string
#  armor_class    :integer
#  armor_type     :string
#  name           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  character_id   :integer
#
class Armor < ApplicationRecord
  validates(:character_id, presence: true)

  belongs_to(:character, class_name: "Character", foreign_key: "character_id")
end

app/controllers/armors_controller.rb
class ArmorsController < ApplicationController
  before_action :set_armor, only: %i[ show edit update destroy ]
  before_action :set_character

  # GET /armors or /armors.json
  def index
    @armors = @character.armors
  end

  # GET /armors/1 or /armors/1.json
  def show
  end

  # GET /armors/new
  def new
    
    @armor = @character.armors.new
  end

  # GET /armors/1/edit
  def edit
    @armor
  end

  # POST /armors or /armors.json
  def create

    @armor = @character.armors.new(armor_params)
    # @armor = Armor.new(armor_params)

    respond_to do |format|
      if @armor.save
        format.html { redirect_to armor_url(@armor), notice: "Armor was successfully created." }
        format.json { render :show, status: :created, location: @armor }
      else
        puts @armor.errors.full_messages
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @armor.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /armors/1 or /armors/1.json
  def update
    respond_to do |format|
      if @armor.update(armor_params)
        format.html { redirect_to (@character), notice: "Armor was successfully updated." }
        format.json { render :show, status: :ok, location: character_armor_url(@character, @armor) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @armor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /armors/1 or /armors/1.json
  def destroy
    @armor.destroy

    respond_to do |format|
      format.html { redirect_to (@character), notice: 'Armor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_armor
    @armor = Armor.find(params[:id])
  end

  def set_character

    @character = Character.find(params[:character_id])
  end

  # Only allow a list of trusted parameters through.
  def armor_params
    params.require(:armor).permit(:armor_class, :armor_category, :armor_type, :name, :character_id)
  end
end

app/views/armors/_armor.html.erb
  
<div id="<%= dom_id armor %>">
  <div class="card"  style="width: 18rem;">
    <ul class="list-group list-group-flush" >
      <li class="list-group-item" id = "details">
        <p>
          <strong>Armor class:</strong>
          <%= armor.armor_class %>
        </p>

        <p>
          <strong>Armor category:</strong>
          <%= armor.armor_category %>
        </p>

        <p>
          <strong>Armor type:</strong>
          <%= armor.armor_type %>
        </p>

        <p>
          <strong>Name:</strong>
          <%= armor.name %>
        </p>
        
        <%= link_to "Edit armor", edit_character_armor_path(@character, armor) %>
        <%= button_to 'Delete armor', character_armor_path(@character, armor), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

      </li>
    </ul>
  </div>

</div>

app/views/armors/_form.html.erb
<%= form_with(model: [@character, @armor], local: true) do |form| %>
  <% if armor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(armor.errors.count, "error") %> prohibited this armor from being saved:</h2>

      <ul>
        <% armor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :armor_class, style: "display: block" %>
    <%= form.number_field :armor_class %>
  </div>

  <div>
    <%= form.label :armor_category, style: "display: block" %>
    <%= form.text_field :armor_category %>
  </div>

  <div>
    <%= form.label :armor_type, style: "display: block" %>
    <%= form.text_field :armor_type %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :character_id, style: "display: block" %>
    <%= form.hidden_field :character_id, value: @character.id %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/armors/_show.html.erb
<p style="color: green"><%= notice %></p>
<%Armor.all.each do |armor|%>
<%= render "armors/armor", armor: armor %>
<% end %>
<!--<div>-->
  <%#= link_to "Edit this armor", edit_armor_path(@armor) %> |
  <%#= link_to "Back to armors", armors_path %>
<!---->
  <%#= button_to "Destroy this armor", @armor, method: :delete %>
<!--</div>-->

app/views/armors/edit.html.erb
<h1>Editing armor</h1>

<%= render "form", armor: @armor %>

<br>

<div>
  <%= link_to "Back to character", (@character) %> 
  
</div>

app/views/armors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Armors</h1>

<div id="armors">
  <% @armors.each do |armor| %>
    <%= render armor %>
    <p>
      <%= link_to "Show this armor", character_armor_path(@character, armor) %>
    </p>
  <% end %>
</div>

<%= link_to "New armor", new_character_armor_path(@character) %>

app/views/armors/new.html.erb
<h1>New armor</h1>

<%= render "form", armor: @armor %>

<br>

<div>
  <%= link_to "Back to armors", character_armors_path(@character) %>
</div>

app/views/armors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @armor %>

<div>
  <%= link_to "Edit this armor", edit_armor_path(@armor) %> |
  <%= link_to "Back to armors", armors_path %>

  <%= button_to "Destroy this armor", @armor, method: :delete %>
</div>